### ISSUE TITLE
Code needs to be commented out properly

### ISSUE THREAD

**Issue by ajayns** [ajayns/c-programs#1]
The programs in the linked list folder are to be commented out and indented properly in reference to `7_circular-doubly-linked-list.c`

**Comment by CodedChai** [comment]
You are looking for adding comments and make sure it's all indented properly, correct? I'm willing to do it.

**Comment by CodedChai** [comment]
Sent pull request

**Comment by ajayns** [comment]
@skrillcon Yes! Thanks, also a suggestion, while making PRs, reference the issue like 'Fixes issue #1' which would be better for both of us. :)

**Comment by CodedChai** [comment]
Ahhh that's a really good suggestion, thank you!
